kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ required "Must provide a storage class name"  .Values.storage.name }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer