- hosts: nodes
  become: true
  tasks:
    - name: Transfer the script 
      copy: src=create-folder.sh dest=/home/user mode=0777
    
    - name: Execute the script
      command: sh /home/user/create-folder.sh
