apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: metricbeat
  namespace: kube-logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metricbeat
subjects:
- kind: ServiceAccount
  name: metricbeat
  namespace: kube-logging
