{{- if .Values.stateMetric.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kube-state-metrics
  name: kube-state-metrics
  namespace: {{ .Values.logNamespace }}
spec:
  selector:
    matchLabels:
      app: kube-state-metrics
  replicas: {{ .Values.stateMetric.replicas }}
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      serviceAccountName: kube-state-metrics
      containers:
      - name: kube-state-metrics
        image: {{ .Values.images.stateMetric }}
        ports:
        - name: http-metrics
          containerPort: {{ .Values.stateMetric.ports.httpmetrics }}
        - name: telemetry
          containerPort:  {{ .Values.stateMetric.ports.telemetry }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
{{- end -}}