{{- if .Values.apmserver.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: apm-server
  namespace: {{ .Values.logNamespace }}
  labels:
    app: apm-server
spec:
  ports:
  - port: {{ .Values.apmserver.ports.container }}
    targetPort: {{ .Values.apmserver.ports.container }}
    name: http
    nodePort: {{ .Values.apmserver.ports.http }}
  selector:
    app: apm-server
  type: NodePort
{{- end -}}